/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab4.nghinc_java3;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author ASUS
 */
public class domo extends javax.swing.JFrame {

    /**
     * Creates new form domo
     */
    public domo() {
        initComponents();
        setLocationRelativeTo(red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btntoolbar_exit = new javax.swing.JButton();
        panne = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        muFile_new = new javax.swing.JMenuItem();
        muFileopen = new javax.swing.JMenuItem();
        mufiilesave = new javax.swing.JMenuItem();
        mufile_exit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        red = new javax.swing.JRadioButtonMenuItem();
        green = new javax.swing.JRadioButtonMenuItem();
        blue = new javax.swing.JRadioButtonMenuItem();
        other = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        munuabout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nghinc_java3/icom/new-icon-16.png"))); // NOI18N
        jButton1.setText("New ");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nghinc_java3/icom/open-file-icon-16.png"))); // NOI18N
        jButton2.setText("Open");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nghinc_java3/icom/Save-icon.png"))); // NOI18N
        jButton3.setText("Save");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator1);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nghinc_java3/icom/Help-icon-16.png"))); // NOI18N
        jButton4.setText("Help");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator2);

        btntoolbar_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nghinc_java3/icom/Actions-edit-delete-icon-16.png"))); // NOI18N
        btntoolbar_exit.setText("Exit");
        btntoolbar_exit.setFocusable(false);
        btntoolbar_exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btntoolbar_exit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btntoolbar_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mufile_exitActionPerformed(evt);
            }
        });
        jToolBar1.add(btntoolbar_exit);

        javax.swing.GroupLayout panneLayout = new javax.swing.GroupLayout(panne);
        panne.setLayout(panneLayout);
        panneLayout.setHorizontalGroup(
            panneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );
        panneLayout.setVerticalGroup(
            panneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        muFile_new.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        muFile_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hh/nghinc_java3/icom/Home-icon-16.png"))); // NOI18N
        muFile_new.setText("New");
        jMenu1.add(muFile_new);

        muFileopen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        muFileopen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hh/nghinc_java3/icom/open-file-icon-16.png"))); // NOI18N
        muFileopen.setText("Open");
        muFileopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muFileopenActionPerformed(evt);
            }
        });
        jMenu1.add(muFileopen);

        mufiilesave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mufiilesave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hh/nghinc_java3/icom/Actions-view-choose-icon-24.png"))); // NOI18N
        mufiilesave.setText("Save");
        jMenu1.add(mufiilesave);

        mufile_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mufile_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hh/nghinc_java3/icom/Actions-edit-delete-icon-16.png"))); // NOI18N
        mufile_exit.setText("Exit");
        mufile_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mufile_exitActionPerformed(evt);
            }
        });
        jMenu1.add(mufile_exit);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Edit");

        jMenu4.setText("Color");

        buttonGroup1.add(red);
        red.setSelected(true);
        red.setText("red");
        red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redActionPerformed(evt);
            }
        });
        jMenu4.add(red);

        buttonGroup1.add(green);
        green.setText("green");
        green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenActionPerformed(evt);
            }
        });
        jMenu4.add(green);

        buttonGroup1.add(blue);
        blue.setText("blue");
        blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueActionPerformed(evt);
            }
        });
        jMenu4.add(blue);

        buttonGroup1.add(other);
        other.setText("Other Color");
        other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherActionPerformed(evt);
            }
        });
        jMenu4.add(other);

        jMenu3.add(jMenu4);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("held");

        jMenuItem5.setText("content");
        jMenu2.add(jMenuItem5);

        munuabout.setText("About ");
        munuabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                munuaboutActionPerformed(evt);
            }
        });
        jMenu2.add(munuabout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(panne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void muFileopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muFileopenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_muFileopenActionPerformed

    private void mufile_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mufile_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mufile_exitActionPerformed

    private void redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redActionPerformed
           Color color = new Color(255,0,0)   ;  
           panne.setBackground(color);
    }//GEN-LAST:event_redActionPerformed

    private void greenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenActionPerformed
         Color color = new Color(0,255,0)   ;  
           panne.setBackground(color);
    }//GEN-LAST:event_greenActionPerformed

    private void blueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueActionPerformed
       Color color = new Color(0,0,255)   ; 
         panne.setBackground(color);
    }//GEN-LAST:event_blueActionPerformed

    private void otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherActionPerformed
      Color color =  JColorChooser.showDialog(this,"choose your color", Color.yellow);
      panne.setBackground(color);
    }//GEN-LAST:event_otherActionPerformed

    private void munuaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_munuaboutActionPerformed
      dialong ialong = new dialong();
      ialong.setVisible(true);
    }//GEN-LAST:event_munuaboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(domo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(domo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(domo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(domo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new domo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem blue;
    private javax.swing.JButton btntoolbar_exit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButtonMenuItem green;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem muFile_new;
    private javax.swing.JMenuItem muFileopen;
    private javax.swing.JMenuItem mufiilesave;
    private javax.swing.JMenuItem mufile_exit;
    private javax.swing.JMenuItem munuabout;
    private javax.swing.JRadioButtonMenuItem other;
    private javax.swing.JPanel panne;
    private javax.swing.JRadioButtonMenuItem red;
    // End of variables declaration//GEN-END:variables
}
